### ISSUE TITLE
Modify search to multiselect dropwown

### ISSUE THREAD

**Issue by Iamslok** [Iamslok/geeksmeet#15]
![image](https://user-images.githubusercontent.com/90669886/210929975-d4664f9c-8255-42d5-8040-65202089010c.png)

Change search input to a multi-select dropdown

**Comment by MitaliGupta111** [comment]
Hi, I am interested in this. Do assign it to me.

**Comment by Iamslok** [comment]
Yeah go ahead

**Comment by Iamslok** [comment]
@MitaliGupta111 Any updates

**Comment by MitaliGupta111** [comment]
I will try do it as soon as possible.
I was suffering from poor health so its not completed yet.

**Comment by Iamslok** [comment]
@MitaliGupta111 yeah take care
