### ISSUE TITLE
Update the Readme.md

### ISSUE THREAD

**Issue by Iamslok** [Iamslok/geeksmeet#17]
> Change the image of the project

**Comment by adityakode** [comment]
Hi!
i would like to help with this one. 
What should I change the image to ?

**Comment by Iamslok** [comment]
Yeah @adityakode 
step 1: fork the project
step 2: Run the project in your local 
step3: Take the screenshot of the project and replace those images in the Readme file

**Comment by adityakode** [comment]
Sure !
Thank you

**Comment by adityakode** [comment]
@Iamslok  here is the screenshot of the project 
![image](https://user-images.githubusercontent.com/105551807/221117972-cb2a6f0f-4e8a-4549-ae86-6de9deaf528a.png)
it this ok ?

**Comment by Iamslok** [comment]
> @Iamslok here is the screenshot of the project ![image](https://user-images.githubusercontent.com/105551807/221117972-cb2a6f0f-4e8a-4549-ae86-6de9deaf528a.png) it this ok ?

Yeah @adityakode it looks nice but can you open the dropdown and take the screenshot

**Comment by Iamslok** [comment]
@adityakode and go to `add your profile` and take a screenshot

**Comment by adityakode** [comment]
Here it is for `Add your profile`
![image](https://user-images.githubusercontent.com/105551807/221122726-8306e00c-6ab4-4af4-ac5a-445365cdecfe.png)

**Comment by adityakode** [comment]
And this is of `dropdown`
![image](https://user-images.githubusercontent.com/105551807/221122907-d2c9955a-237c-444d-94ec-60682f05d0f8.png)

**Comment by adityakode** [comment]
@Iamslok should I change and add all 3 images to Readme?

**Comment by Iamslok** [comment]
Yeah @adityakode looks nice to replace these images in the readme file and create a pull request

**Comment by Iamslok** [comment]
> @Iamslok should I change and add all 3 images to Readme?

yeah

**Comment by adityakode** [comment]
keeping the sequence like this:
1.`project` image
2.`dropdown` image
2.`add profile` image

**Comment by Iamslok** [comment]
i'll share a meetlink here can you attend

**Comment by adityakode** [comment]
sure!

**Comment by Iamslok** [comment]
https://meet.google.com/bwa-qaxq-iwk?pli=1

**Comment by adityakode** [comment]
@Iamslok sent a PR #18 
Ps check if ok

**Comment by Iamslok** [comment]
Thank you for your contribution
