### ISSUE TITLE
Improve profile cards design

### ISSUE THREAD

**Issue by Iamslok** [Iamslok/geeksmeet#6]
<img width="917" alt="image" src="https://user-images.githubusercontent.com/90669886/210132877-b50acfb0-a788-4202-9f45-b86b42df5510.png">

**Comment by Blackflare002** [comment]
Hi again, I'd like to try doing this. Did you have anything specific in mind for the styling?

**Comment by Iamslok** [comment]
@Blackflare002 I don't have anything in my mind, you can try on your own

**Comment by Iamslok** [comment]
@Blackflare002 I don't have anything in my mind, but you can try it on your own
